//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EJ1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customers
    {
        public int CustomerID { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Name { get; set; }

        [RegularExpression(@"^\d{8}$", ErrorMessage = "El campo debe contener 8 dígitos")]
        [Required(ErrorMessage = "El numero de documento es obligatorio")]
        public string DocumentNumber { get; set; }

        [StringLength(20,ErrorMessage = "El nombre debe tener 20 caracteres")]
        [Required(ErrorMessage = "El Tipo de documento es obligatorio")]
        public string DocumentType { get; set; }
        public bool IsActive { get; set; }
    }
}
